/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 14/11/2019 09:17:02          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'EBER-1963:E:\Prototipos\Executaveis\DB\DADOS.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_SERVIDOR;
SET GENERATOR GEN_SERVIDOR TO 26;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE SERVIDOR (
    ID            INTEGER NOT NULL,
    NOMESERVIDOR  VARCHAR(250),
    PATHSERVIDOR  VARCHAR(250),
    PORTA         INTEGER
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE SERVIDOR ADD CONSTRAINT PK_SERVIDOR PRIMARY KEY (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: SERVIDOR_BI0 */
CREATE TRIGGER SERVIDOR_BI0 FOR SERVIDOR
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  new.id = gen_id(GEN_SERVIDOR, 1);
end
^

SET TERM ; ^

